version: '3'
services:
  cluster:
    image: grokzen/redis-cluster:5.0.5
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
  proxy:
    depends_on:
      - cluster
    image: redis-cluster-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LISTEN_ADDR=:8000
      - CLUSTER_ADDR=cluster:7000
      - START_DELAY=10s
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
